# Site settings
title: Junhao's Page
description: This is the introduction about Junhao
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Junhao Duan
user_description:  I am passionate in data analysis. I can use python and R. Knowing algorithm and models. Interested in linear algebra and possibility.
user_title: Data Analyst
email: harmonyduan@gmail.com
#twitter_username: lorem_ipsum
github_username:  junhaod.github.io
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
